"""Reusable CSI data, device, environment, and analysis primitives."""

from .dataset import (
    NormalizedRun,
    NormalizedTrialCapture,
    RunCapture,
    load_labeled_run_dirs,
    load_labeled_runs,
    load_normalized_runs,
    validate_run_metadata,
)
from .domain import (
    CANONICAL_SCHEMA_NAME,
    CANONICAL_SCHEMA_VERSION,
    AcquisitionBlock,
    DerivedFeatureSet,
    DeviceProfile,
    EvaluationReport,
    ExperimentDefinition,
    Geometry,
    GroundTruth,
    LabelSet,
    PacketRecord,
    RunManifest,
    RunProvenance,
    ScenarioRef,
    SubjectRef,
    TrainedModelArtifact,
    TrialDefinition,
)
from .device import (
    DEFAULT_SERIAL_DEVICE,
    DEVICE_ENV_VARS,
    DeviceAccessError,
    ResolvedDevice,
    list_serial_candidates,
    resolve_serial_device,
    validate_serial_device_access,
)
from .environment import (
    DEFAULT_ENVIRONMENT_PROFILE_ID,
    EnvironmentProfile,
    EnvironmentProfileError,
    format_environment_banner,
    list_environment_profiles,
    resolve_environment_profile,
)

__all__ = [
    "DEFAULT_SERIAL_DEVICE",
    "DEFAULT_ENVIRONMENT_PROFILE_ID",
    "DEVICE_ENV_VARS",
    "DeviceAccessError",
    "DeviceProfile",
    "DerivedFeatureSet",
    "EnvironmentProfile",
    "EnvironmentProfileError",
    "EvaluationReport",
    "ExperimentDefinition",
    "Geometry",
    "GroundTruth",
    "LabelSet",
    "NormalizedRun",
    "NormalizedTrialCapture",
    "PacketRecord",
    "ResolvedDevice",
    "format_environment_banner",
    "list_environment_profiles",
    "RunCapture",
    "RunManifest",
    "RunProvenance",
    "ScenarioRef",
    "SubjectRef",
    "TrainedModelArtifact",
    "TrialDefinition",
    "CANONICAL_SCHEMA_NAME",
    "CANONICAL_SCHEMA_VERSION",
    "list_serial_candidates",
    "load_labeled_run_dirs",
    "load_labeled_runs",
    "load_normalized_runs",
    "resolve_environment_profile",
    "resolve_serial_device",
    "validate_run_metadata",
    "validate_serial_device_access",
]
